[env]
TERM = "xterm-256color"

[general]
import = [
	".alacritty.local.toml",
]
live_config_reload = true

[window]
decorations = "none"
opacity = 0.99
dynamic_title = true
padding = { x = 10, y = 10 }

[window.dimensions]
columns = 80
lines = 25

[font]
normal = { family = "MonaspiceKr NF" }
offset = { x = 0, y = 4 }
