"$schema" = 'https://starship.rs/config-schema.json'

# add_newline = false

[directory]
read_only = " "
truncation_length = 10
truncate_to_repo = true

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](bold red)'

[battery]
disabled = true

[golang]
symbol = " "

[python]
symbol = " "

[c]
symbol = " "

[rust]
symbol = " "

[docker_context]
disabled = true

[custom.bartib]
format = '[󰥔 $output]($style) '
style = "#767676"
command = "bartib current | sed -n '3p' | cut -d' ' -f'3-' | sed -E 's/\\xC2\\xA0+//g; s/[^,](([0-9]+h )?<?[0-9]+m)/,\\1/; s/ ([^ ]+),/,\\1,/' | awk -F',' '{print $3, \"[\"$2\"]\", $1}'"
shell = ["sh", "--norc"]
when = "bartib current | grep -q -v 'No Activity is currently running'"
