[snippets]
custom_paths = []
include_default_snippets = true

[runtime]
reactive_tests = true
auto_instantiate = false
default_auto_download = []
default_sql_output = "auto"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"
on_cell_change = "autorun"
auto_reload = "off"

[server]
browser = "default"
follow_symlink = false

[keymap]
preset = "vim"
destructive_delete = true

[keymap.overrides]

[experimental]

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[package_management]
manager = "uv"

[formatting]
line_length = 79

[language_servers.basedpyright]

[language_servers.ty]

[language_servers.pylsp]
enable_pydocstyle = false
enabled = true
enable_mypy = true
enable_flake8 = false
enable_pyflakes = false
enable_ruff = true
enable_pylint = false

[display]
cell_output = "below"
theme = "system"
code_editor_font_size = 14
dataframes = "rich"
default_table_page_size = 10
default_table_max_columns = 50
default_width = "medium"
reference_highlighting = false

[completion]
activate_on_typing = true
copilot = false

[diagnostics]
sql_linter = true
